
!ENTRY com.aptana.shared_core 4 4 2013-04-05 16:13:21.467
!MESSAGE Info: Rebuilding internal caches: /home/tnurlygayanov/keero/conductor/tests/.metadata/.plugins/com.python.pydev.analysis/python_v1_3tswbhuj9gc4kibexhrzgzdx/python.pydevsysteminfo (Expected error to be provided and got no error!)

!ENTRY org.eclipse.jface.text 4 0 2013-04-05 16:29:20.772
!MESSAGE Unexpected runtime error while computing a text hover
!STACK 0
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: No such file or directory
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:88)
	at org.python.pydev.editor.hover.PyTextHover.getDocstringHover(PyTextHover.java:206)
	at org.python.pydev.editor.hover.PyTextHover.getHoverInfo(PyTextHover.java:150)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:168)
Caused by: java.lang.RuntimeException: java.io.IOException: No such file or directory
	at org.python.pydev.core.DeltaSaver.addCommand(DeltaSaver.java:254)
	at org.python.pydev.core.DeltaSaver.addInsertCommand(DeltaSaver.java:293)
	at org.python.pydev.editor.codecompletion.revisited.ModulesManagerWithBuild.doAddSingleModule(ModulesManagerWithBuild.java:112)
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.getModule(ModulesManager.java:895)
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.getModule(ModulesManager.java:718)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getRelativeModule(SystemModulesManager.java:139)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.getModule(AbstractASTManager.java:446)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.findModuleFromPath(AbstractASTManager.java:1430)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.findOnImportedMods(AbstractASTManager.java:1289)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.findOnImportedMods(AbstractASTManager.java:1200)
	at org.python.pydev.editor.codecompletion.revisited.AbstractASTManager.findOnImportedMods(AbstractASTManager.java:1167)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:866)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:779)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:657)
	at org.python.pydev.editor.codecompletion.revisited.modules.SourceModule.findDefinition(SourceModule.java:1)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:179)
	at org.python.pydev.editor.refactoring.PyRefactoringFindDefinition.findActualDefinition(PyRefactoringFindDefinition.java:81)
	... 3 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:947)
	at org.python.pydev.core.DeltaSaver.addCommand(DeltaSaver.java:252)
	... 19 more
